apiVersion: v1
data:
  admin.enabled: "true"
  users.anonymous.enabled: "true"
  users.anonymous.role: admin
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"admin.enabled":"true"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"server","app.kubernetes.io/name":"argocd-cm","app.kubernetes.io/part-of":"argocd"},"name":"argocd-cm","namespace":"argocd"}}
  creationTimestamp: "2026-10-07T22:18:26Z"
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
  resourceVersion: "2062462"
  uid: d505f864-b3fb-41b9-b38f-21b115a02f16
