apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: password-api-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com' # ה-Repo שלך
    targetRevision: main # עוקב אחרי בראנץ' main
    path: helm-chart     # התיקייה שבה נמצא ה-Chart.yaml
    helm:
      valueFiles:
        - ../environments/Dev/values-dev.yaml # הזרקת הערכים הייחודיים של Dev
  destination:
    server: 'https://default.svc'
    namespace: dev-apps # ה-Namespace באשכול שבו תרוץ האפליקציה של ה-Flask API
  syncPolicy:
    createNamespace: true # יצור את dev-apps אוטומטית
    automated:
      prune: true
      selfHeal: true      # תיקון אוטומטי במקרה של שינוי ידני
