apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: password-api-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/elirangz1-creator/my-k8s-monitoring-project.git' # My-Repo
    targetRevision: main # 'folow  main brunch
    path: helm-chart     # -Chart.yaml forder
    helm:
      valueFiles:
        - ../environments/Dev/values-dev.yaml   #Unic dev values 
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev-apps # - Cluster Namespace for Flask API app. to run
  syncPolicy:
    createNamespace: true # auto creation of dev-apps
    automated:
      prune: true
      selfHeal: true      # auto repair in case of manual change

