apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }} # מושך את כמות הרפליקות דינמית
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
      annotations:
        # הגדרה המאפשרת ל-Prometheus לזהות ולגרד (Scrape) את ה-Metrics של Flask אוטומטית!
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}" # מושך את ה-Image מה-Values
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 5000 # הפורט של אפליקציית הפייתון שלך
        # הגדרת בדיקת תקינות המבוססת על ה-Health Check שכתבת בקוד
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
