apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  type: {{ .Values.service.type }} # ישתמש ב-ClusterIP כברירת מחדל
  ports:
  - port: {{ .Values.service.port }} # פורט 5000
    targetPort: 5000
    protocol: TCP
  selector:
    app: {{ .Chart.Name }}
